### PR TITLE
Allow qlScheduleTruncated to return dates after truncation date too

### PR DESCRIPTION
**Pull request by igitur**
This requires https://github.com/lballabio/QuantLib/pull/655 to be merged first.

### CODE REVIEW

**Comment by eehlers** [comment]
Looks like the prerequisite has not yet been merged?

**Comment by igitur** [comment]
https://github.com/lballabio/QuantLib/pull/655 is merged now, but will be released only in v1.17 of QuantLib.

**Comment by eehlers** [comment]
OK

**Comment by eehlers** [comment]
I merged this to v1.17.x and included it in the prerelease build that I will deploy momentarily.  Many thanks for the contribution, any problems please let me know.

**Comment by igitur** [comment]
Great, thanks

**Pull request closed without merging**
