### PR TITLE
Consolidate project files and upgrade to VS2019

### PR DESCRIPTION
**Pull request by igitur**
Hi, as discussed in email, let's simplify the project structure.

This PR:

- Deletes the `*_vc*.vcxproj` and `*_vc*.sln` files 
- Amends the remaining `.vcxproj` files to use QuantLib's .props file, which sets the `PlatformToolset` variable
- Builds `.lib` files using `PlatformToolset` instead of `qlaCompilerTag`, `ohCompilerTag`, etc
- Update `auto_link.hpp` for VS2019

### CODE REVIEW

**Comment by igitur** [comment]
Please consider rebasing instead of merging to keep the commit history cleaner.

**Comment by igitur** [comment]
Hi Eric. Any chance of giving this repo some love?

**Comment by eehlers** [comment]
Working on it now.

**Comment by eehlers** [comment]
Merged to master and v1.20.x.  This is a great cleanup, many thanks!

**Pull request merged**
