### PR TITLE
Add Payment lag parameter to OIS Rate Helper and MakeOIS

### PR DESCRIPTION
**Pull request by bnalgo**

### CODE REVIEW

**Comment by eehlers** [comment]
many thanks, i will look at this when i package the next release.

**Comment by RogKle** [comment]
many thanks as well! What about the function qlSchedule to value a running OIS by using qlOvernightIndexedSwap?

**Comment by bnalgo** [comment]
The PaymentLag parameter applies to the qlMakeOIS function rather than qlSchedule. 
I've just pushed an update that adds this parameter to the qlOvernightIndexedSwap function too

**Comment by eehlers** [comment]
thank you very much.  i will include this when i package the 1.15 release.  how do you want to be credited on page https://www.quantlib.org/quantlibxl/history.html? "Thanks to bnalgo"?

**Comment by bnalgo** [comment]
If you could use  "Thanks to BN Algorithms Ltd"  that would be best -- thanks

**Comment by eehlers** [comment]
will do.

**Comment by eehlers** [comment]
oh, wait, i recognize you :)  are you in cambridge?  my girlfriend and i have booked a weekend away to cambridge 7-10 march, i'd be delighted to buy you a beer if you are free.

**Comment by bnalgo** [comment]
Yes, that is me :)  Should be free in the late evenings, would be great to meet up for a quick beer -- drop me an email at bnalgorithms@bnikolic.co.uk and I'll send you my mobile number

**Comment by eehlers** [comment]
Merged to v1.16.x.

**Pull request closed without merging**
