### PR TITLE
Upgrade gensrc to python3

### PR DESCRIPTION
**Pull request by igitur**
Preliminary python3 support for the gensrc scripts. I didn't dig very deep. I used the `2to3` tool and then manually fixed a few additional issues. Building `QuantLibXL` now works fine using the `python3` interpreter, but I can't say for sure whether all changes across all the files have been changed.

My suggestion is we merge this and then fix the additional issues as they arise. As far as I understand, besides the Excel plugin, this repo isn't really used for anything else anymore.

### CODE REVIEW

**Comment by eehlers** [comment]
Merged, many thanks.  I still maintain the C++ addin and I will update the source code generation for that if necessary.

**Comment by igitur** [comment]
Thanks. What exactly is the C++ addin? How is that different to normal QuantLib?

**Comment by eehlers** [comment]
It exports the QuantLibAddin interface to C++.  So from C++ you could call the same functions that are supported in QuantLibXL.  I have used it for grid computing.

**Comment by igitur** [comment]
Oh, I remember now you mentioned something about this in the mailing list recently. That's really cool. Wish I could get my hands on a grid computing infrastructure.

**Pull request closed without merging**
